version: '3.7'

services:
  go:
    image: golang:1.11.0
    working_dir: /go/src/github.com/sawadashota/jwt-sample
    environment:
      ID_RSA_PATH: "/go/src/github.com/sawadashota/jwt-sample/certs/id_rsa"
      ID_RSA_PUBLIC_PATH: "/go/src/github.com/sawadashota/jwt-sample/certs/id_rsa.pub.pkcs8"
    volumes:
      - .:/go/src/github.com/sawadashota/jwt-sample
    expose:
      - 8080
    ports:
      - 8080:8080
    command: go run main.go
